package com.ns.common.model;

import com.ns.common.model.base.BaseBasCustomerCart;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BasCustomerCart extends BaseBasCustomerCart<BasCustomerCart> {
	public static final BasCustomerCart dao = new BasCustomerCart().dao();
}
