package com.ns.common.model;

import com.ns.common.model.base.BaseTldAwardMid;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TldAwardMid extends BaseTldAwardMid<TldAwardMid> {
	public static final TldAwardMid dao = new TldAwardMid().dao();
}
