package com.ns.common.model;

import com.ns.common.model.base.BaseTldAwardContract;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TldAwardContract extends BaseTldAwardContract<TldAwardContract> {
	public static final TldAwardContract dao = new TldAwardContract().dao();
}
