package com.ns.common.model;

import com.ns.common.model.base.BaseTldAward;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TldAward extends BaseTldAward<TldAward> {
	public static final TldAward dao = new TldAward().dao();
}
