package com.ns.common.model;

import com.ns.common.model.base.BaseTldOrderAward;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TldOrderAward extends BaseTldOrderAward<TldOrderAward> {
	public static final TldOrderAward dao = new TldOrderAward().dao();
}
