package com.ns.common.model;

import com.ns.common.model.base.BaseTldPntParams;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TldPntParams extends BaseTldPntParams<TldPntParams> {
	public static final TldPntParams dao = new TldPntParams().dao();
}
