package com.ns.common.model;

import com.ns.common.model.base.BaseTldParams;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TldParams extends BaseTldParams<TldParams> {
	public static final TldParams dao = new TldParams().dao();
}
