package com.ns.common.model;

import com.ns.common.model.base.BaseTldRebateFlow;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TldRebateFlow extends BaseTldRebateFlow<TldRebateFlow> {
	public static final TldRebateFlow dao = new TldRebateFlow().dao();
}
