package com.ns.common.model;

import com.ns.common.model.base.BaseTldTwitter;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TldTwitter extends BaseTldTwitter<TldTwitter> {
	public static final TldTwitter dao = new TldTwitter().dao();
}
