package com.ns.common.model;

import com.ns.common.model.base.BaseTldWithdraw;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TldWithdraw extends BaseTldWithdraw<TldWithdraw> {
	public static final TldWithdraw dao = new TldWithdraw().dao();
}
