package com.ns.common.model;

import com.ns.common.model.base.BaseTldWechatWithdraw;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TldWechatWithdraw extends BaseTldWechatWithdraw<TldWechatWithdraw> {
	public static final TldWechatWithdraw dao = new TldWechatWithdraw().dao();
}
