package com.ns.common.model;

import com.ns.common.model.base.BaseTldWithdrawItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TldWithdrawItem extends BaseTldWithdrawItem<TldWithdrawItem> {
	public static final TldWithdrawItem dao = new TldWithdrawItem().dao();
}
