package com.ns.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTldOrderAward<M extends BaseTldOrderAward<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setOrderId(java.lang.String orderId) {
		set("order_id", orderId);
		return (M)this;
	}
	
	public java.lang.String getOrderId() {
		return getStr("order_id");
	}

	public M setOrderNo(java.lang.String orderNo) {
		set("order_no", orderNo);
		return (M)this;
	}
	
	public java.lang.String getOrderNo() {
		return getStr("order_no");
	}

	public M setConId(java.lang.String conId) {
		set("con_id", conId);
		return (M)this;
	}
	
	public java.lang.String getConId() {
		return getStr("con_id");
	}

	public M setConNo(java.lang.String conNo) {
		set("con_no", conNo);
		return (M)this;
	}
	
	public java.lang.String getConNo() {
		return getStr("con_no");
	}

	public M setOrderStatsId(java.lang.String orderStatsId) {
		set("order_stats_id", orderStatsId);
		return (M)this;
	}
	
	public java.lang.String getOrderStatsId() {
		return getStr("order_stats_id");
	}

	public M setShopComm(java.math.BigDecimal shopComm) {
		set("shop_comm", shopComm);
		return (M)this;
	}
	
	public java.math.BigDecimal getShopComm() {
		return get("shop_comm");
	}

	public M setVersion(java.math.BigDecimal version) {
		set("version", version);
		return (M)this;
	}
	
	public java.math.BigDecimal getVersion() {
		return get("version");
	}

	public M setUpdateDt(java.lang.String updateDt) {
		set("update_dt", updateDt);
		return (M)this;
	}
	
	public java.lang.String getUpdateDt() {
		return getStr("update_dt");
	}

	public M setCreateDt(java.lang.String createDt) {
		set("create_dt", createDt);
		return (M)this;
	}
	
	public java.lang.String getCreateDt() {
		return getStr("create_dt");
	}

	public M setLevel(java.lang.String level) {
		set("level", level);
		return (M)this;
	}
	
	public java.lang.String getLevel() {
		return getStr("level");
	}

	public M setAwardConId(java.lang.String awardConId) {
		set("award_con_id", awardConId);
		return (M)this;
	}
	
	public java.lang.String getAwardConId() {
		return getStr("award_con_id");
	}

	public M setAwardConNo(java.lang.String awardConNo) {
		set("award_con_no", awardConNo);
		return (M)this;
	}
	
	public java.lang.String getAwardConNo() {
		return getStr("award_con_no");
	}

	public M setProductAmount(java.math.BigDecimal productAmount) {
		set("product_amount", productAmount);
		return (M)this;
	}
	
	public java.math.BigDecimal getProductAmount() {
		return get("product_amount");
	}

	public M setErrorFlag(java.lang.Integer errorFlag) {
		set("error_flag", errorFlag);
		return (M)this;
	}
	
	public java.lang.Integer getErrorFlag() {
		return getInt("error_flag");
	}

	public M setPayDate(java.lang.String payDate) {
		set("pay_date", payDate);
		return (M)this;
	}
	
	public java.lang.String getPayDate() {
		return getStr("pay_date");
	}

	public M setProductId(java.lang.String productId) {
		set("product_id", productId);
		return (M)this;
	}
	
	public java.lang.String getProductId() {
		return getStr("product_id");
	}

	public M setProductName(java.lang.String productName) {
		set("product_name", productName);
		return (M)this;
	}
	
	public java.lang.String getProductName() {
		return getStr("product_name");
	}

	public M setIsReorder(java.lang.Integer isReorder) {
		set("is_reorder", isReorder);
		return (M)this;
	}
	
	public java.lang.Integer getIsReorder() {
		return getInt("is_reorder");
	}

	public M setConName(java.lang.String conName) {
		set("con_name", conName);
		return (M)this;
	}
	
	public java.lang.String getConName() {
		return getStr("con_name");
	}

	public M setIsSendmsg(java.lang.Integer isSendmsg) {
		set("is_sendmsg", isSendmsg);
		return (M)this;
	}
	
	public java.lang.Integer getIsSendmsg() {
		return getInt("is_sendmsg");
	}

	public M setSkuId(java.lang.String skuId) {
		set("sku_id", skuId);
		return (M)this;
	}
	
	public java.lang.String getSkuId() {
		return getStr("sku_id");
	}

	public M setSkuImageUrl(java.lang.String skuImageUrl) {
		set("sku_image_url", skuImageUrl);
		return (M)this;
	}
	
	public java.lang.String getSkuImageUrl() {
		return getStr("sku_image_url");
	}

	public M setSkuValueNames(java.lang.String skuValueNames) {
		set("sku_value_names", skuValueNames);
		return (M)this;
	}
	
	public java.lang.String getSkuValueNames() {
		return getStr("sku_value_names");
	}

}
