package com.ns.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTldTwitter<M extends BaseTldTwitter<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setPostNo(java.lang.String postNo) {
		set("post_no", postNo);
		return (M)this;
	}
	
	public java.lang.String getPostNo() {
		return getStr("post_no");
	}

	public M setPostName(java.lang.String postName) {
		set("post_name", postName);
		return (M)this;
	}
	
	public java.lang.String getPostName() {
		return getStr("post_name");
	}

	public M setConId(java.lang.String conId) {
		set("con_id", conId);
		return (M)this;
	}
	
	public java.lang.String getConId() {
		return getStr("con_id");
	}

	public M setConNo(java.lang.String conNo) {
		set("con_no", conNo);
		return (M)this;
	}
	
	public java.lang.String getConNo() {
		return getStr("con_no");
	}

	public M setConName(java.lang.String conName) {
		set("con_name", conName);
		return (M)this;
	}
	
	public java.lang.String getConName() {
		return getStr("con_name");
	}

	public M setMobile(java.lang.String mobile) {
		set("mobile", mobile);
		return (M)this;
	}
	
	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	public M setEnable(java.lang.Integer enable) {
		set("enable", enable);
		return (M)this;
	}
	
	public java.lang.Integer getEnable() {
		return getInt("enable");
	}

	public M setVersion(java.lang.Integer version) {
		set("version", version);
		return (M)this;
	}
	
	public java.lang.Integer getVersion() {
		return getInt("version");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setMemo(java.lang.String memo) {
		set("memo", memo);
		return (M)this;
	}
	
	public java.lang.String getMemo() {
		return getStr("memo");
	}

	public M setMinDate(java.lang.String minDate) {
		set("min_date", minDate);
		return (M)this;
	}
	
	public java.lang.String getMinDate() {
		return getStr("min_date");
	}

	public M setYear(java.lang.String year) {
		set("year", year);
		return (M)this;
	}
	
	public java.lang.String getYear() {
		return getStr("year");
	}

	public M setMonth(java.lang.String month) {
		set("month", month);
		return (M)this;
	}
	
	public java.lang.String getMonth() {
		return getStr("month");
	}

	public M setDay(java.lang.String day) {
		set("day", day);
		return (M)this;
	}
	
	public java.lang.String getDay() {
		return getStr("day");
	}

	public M setPercent(java.math.BigDecimal percent) {
		set("percent", percent);
		return (M)this;
	}
	
	public java.math.BigDecimal getPercent() {
		return get("percent");
	}

	public M setIsFirstMonth(java.lang.Integer isFirstMonth) {
		set("is_first_month", isFirstMonth);
		return (M)this;
	}
	
	public java.lang.Integer getIsFirstMonth() {
		return getInt("is_first_month");
	}

	public M setUpNo(java.lang.String upNo) {
		set("up_no", upNo);
		return (M)this;
	}
	
	public java.lang.String getUpNo() {
		return getStr("up_no");
	}

	public M setUpName(java.lang.String upName) {
		set("up_name", upName);
		return (M)this;
	}
	
	public java.lang.String getUpName() {
		return getStr("up_name");
	}

	public M setRebateUpNo(java.lang.String rebateUpNo) {
		set("rebate_up_no", rebateUpNo);
		return (M)this;
	}
	
	public java.lang.String getRebateUpNo() {
		return getStr("rebate_up_no");
	}

	public M setRebateUpName(java.lang.String rebateUpName) {
		set("rebate_up_name", rebateUpName);
		return (M)this;
	}
	
	public java.lang.String getRebateUpName() {
		return getStr("rebate_up_name");
	}

	public M setRefereeId(java.lang.String refereeId) {
		set("referee_id", refereeId);
		return (M)this;
	}
	
	public java.lang.String getRefereeId() {
		return getStr("referee_id");
	}

	public M setRefereeName(java.lang.String refereeName) {
		set("referee_name", refereeName);
		return (M)this;
	}
	
	public java.lang.String getRefereeName() {
		return getStr("referee_name");
	}

	public M setMonthSale(java.math.BigDecimal monthSale) {
		set("month_sale", monthSale);
		return (M)this;
	}
	
	public java.math.BigDecimal getMonthSale() {
		return get("month_sale");
	}

	public M setUnconfirmDirectPush(java.lang.Integer unconfirmDirectPush) {
		set("unconfirm_direct_push", unconfirmDirectPush);
		return (M)this;
	}
	
	public java.lang.Integer getUnconfirmDirectPush() {
		return getInt("unconfirm_direct_push");
	}

	public M setUnconfirmConTotal(java.lang.Integer unconfirmConTotal) {
		set("unconfirm_con_total", unconfirmConTotal);
		return (M)this;
	}
	
	public java.lang.Integer getUnconfirmConTotal() {
		return getInt("unconfirm_con_total");
	}

	public M setConfirmedDirectPush(java.lang.Integer confirmedDirectPush) {
		set("confirmed_direct_push", confirmedDirectPush);
		return (M)this;
	}
	
	public java.lang.Integer getConfirmedDirectPush() {
		return getInt("confirmed_direct_push");
	}

	public M setConfirmedConTotal(java.lang.Integer confirmedConTotal) {
		set("confirmed_con_total", confirmedConTotal);
		return (M)this;
	}
	
	public java.lang.Integer getConfirmedConTotal() {
		return getInt("confirmed_con_total");
	}

	public M setUnconfirmPromotionOrder(java.lang.Integer unconfirmPromotionOrder) {
		set("unconfirm_promotion_order", unconfirmPromotionOrder);
		return (M)this;
	}
	
	public java.lang.Integer getUnconfirmPromotionOrder() {
		return getInt("unconfirm_promotion_order");
	}

	public M setConfirmedPromotionOrder(java.lang.Integer confirmedPromotionOrder) {
		set("confirmed_promotion_order", confirmedPromotionOrder);
		return (M)this;
	}
	
	public java.lang.Integer getConfirmedPromotionOrder() {
		return getInt("confirmed_promotion_order");
	}

	public M setUnconfirmPromotionFee(java.math.BigDecimal unconfirmPromotionFee) {
		set("unconfirm_promotion_fee", unconfirmPromotionFee);
		return (M)this;
	}
	
	public java.math.BigDecimal getUnconfirmPromotionFee() {
		return get("unconfirm_promotion_fee");
	}

	public M setConfirmedPromotionFee(java.math.BigDecimal confirmedPromotionFee) {
		set("confirmed_promotion_fee", confirmedPromotionFee);
		return (M)this;
	}
	
	public java.math.BigDecimal getConfirmedPromotionFee() {
		return get("confirmed_promotion_fee");
	}

	public M setUnconfirmOrder(java.lang.Integer unconfirmOrder) {
		set("unconfirm_order", unconfirmOrder);
		return (M)this;
	}
	
	public java.lang.Integer getUnconfirmOrder() {
		return getInt("unconfirm_order");
	}

	public M setConfirmedOrder(java.lang.Integer confirmedOrder) {
		set("confirmed_order", confirmedOrder);
		return (M)this;
	}
	
	public java.lang.Integer getConfirmedOrder() {
		return getInt("confirmed_order");
	}

	public M setUnconfirmScale(java.math.BigDecimal unconfirmScale) {
		set("unconfirm_scale", unconfirmScale);
		return (M)this;
	}
	
	public java.math.BigDecimal getUnconfirmScale() {
		return get("unconfirm_scale");
	}

	public M setConfirmedScale(java.math.BigDecimal confirmedScale) {
		set("confirmed_scale", confirmedScale);
		return (M)this;
	}
	
	public java.math.BigDecimal getConfirmedScale() {
		return get("confirmed_scale");
	}

	public M setRequestAmount(java.math.BigDecimal requestAmount) {
		set("request_amount", requestAmount);
		return (M)this;
	}
	
	public java.math.BigDecimal getRequestAmount() {
		return get("request_amount");
	}

	public M setRequestedTotal(java.math.BigDecimal requestedTotal) {
		set("requested_total", requestedTotal);
		return (M)this;
	}
	
	public java.math.BigDecimal getRequestedTotal() {
		return get("requested_total");
	}

	public M setReserveAvailable(java.math.BigDecimal reserveAvailable) {
		set("reserve_available", reserveAvailable);
		return (M)this;
	}
	
	public java.math.BigDecimal getReserveAvailable() {
		return get("reserve_available");
	}

	public M setBalanceAmount(java.math.BigDecimal balanceAmount) {
		set("balance_amount", balanceAmount);
		return (M)this;
	}
	
	public java.math.BigDecimal getBalanceAmount() {
		return get("balance_amount");
	}

	public M setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
		return (M)this;
	}
	
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}

	public M setCreateDt(java.lang.String createDt) {
		set("create_dt", createDt);
		return (M)this;
	}
	
	public java.lang.String getCreateDt() {
		return getStr("create_dt");
	}

	public M setUpdateDt(java.lang.String updateDt) {
		set("update_dt", updateDt);
		return (M)this;
	}
	
	public java.lang.String getUpdateDt() {
		return getStr("update_dt");
	}

}
