package com.ns.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBasCustomerCart<M extends BaseBasCustomerCart<M>> extends Model<M> implements IBean {

	public M setCartId(java.lang.String cartId) {
		set("cart_id", cartId);
		return (M)this;
	}
	
	public java.lang.String getCartId() {
		return getStr("cart_id");
	}

	public M setProductId(java.lang.String productId) {
		set("product_id", productId);
		return (M)this;
	}
	
	public java.lang.String getProductId() {
		return getStr("product_id");
	}

	public M setProductName(java.lang.String productName) {
		set("product_name", productName);
		return (M)this;
	}
	
	public java.lang.String getProductName() {
		return getStr("product_name");
	}

	public M setProductImageUrl(java.lang.String productImageUrl) {
		set("product_image_url", productImageUrl);
		return (M)this;
	}
	
	public java.lang.String getProductImageUrl() {
		return getStr("product_image_url");
	}

	public M setSkuId(java.lang.String skuId) {
		set("sku_id", skuId);
		return (M)this;
	}
	
	public java.lang.String getSkuId() {
		return getStr("sku_id");
	}

	public M setSkuName(java.lang.String skuName) {
		set("sku_name", skuName);
		return (M)this;
	}
	
	public java.lang.String getSkuName() {
		return getStr("sku_name");
	}

	public M setSkuImageUrl(java.lang.String skuImageUrl) {
		set("sku_image_url", skuImageUrl);
		return (M)this;
	}
	
	public java.lang.String getSkuImageUrl() {
		return getStr("sku_image_url");
	}

	public M setProductNum(java.lang.Integer productNum) {
		set("product_num", productNum);
		return (M)this;
	}
	
	public java.lang.Integer getProductNum() {
		return getInt("product_num");
	}

	public M setProductPrice(java.math.BigDecimal productPrice) {
		set("product_price", productPrice);
		return (M)this;
	}
	
	public java.math.BigDecimal getProductPrice() {
		return get("product_price");
	}

	public M setReProductPrice(java.math.BigDecimal reProductPrice) {
		set("re_product_price", reProductPrice);
		return (M)this;
	}
	
	public java.math.BigDecimal getReProductPrice() {
		return get("re_product_price");
	}

	public M setSkuPrice(java.math.BigDecimal skuPrice) {
		set("sku_price", skuPrice);
		return (M)this;
	}
	
	public java.math.BigDecimal getSkuPrice() {
		return get("sku_price");
	}

	public M setReSkuPrice(java.math.BigDecimal reSkuPrice) {
		set("re_sku_price", reSkuPrice);
		return (M)this;
	}
	
	public java.math.BigDecimal getReSkuPrice() {
		return get("re_sku_price");
	}

	public M setIsSelected(java.lang.Integer isSelected) {
		set("is_selected", isSelected);
		return (M)this;
	}
	
	public java.lang.Integer getIsSelected() {
		return getInt("is_selected");
	}

	public M setCreator(java.lang.String creator) {
		set("creator", creator);
		return (M)this;
	}
	
	public java.lang.String getCreator() {
		return getStr("creator");
	}

	public M setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.lang.String getCreateTime() {
		return getStr("create_time");
	}

	public M setUpdateTime(java.lang.String updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.lang.String getUpdateTime() {
		return getStr("update_time");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

}
