package com.ns.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTldWithdrawItem<M extends BaseTldWithdrawItem<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setConId(java.lang.String conId) {
		set("con_id", conId);
		return (M)this;
	}
	
	public java.lang.String getConId() {
		return getStr("con_id");
	}

	public M setDrawType(java.lang.String drawType) {
		set("draw_type", drawType);
		return (M)this;
	}
	
	public java.lang.String getDrawType() {
		return getStr("draw_type");
	}

	public M setAmout(java.math.BigDecimal amout) {
		set("amout", amout);
		return (M)this;
	}
	
	public java.math.BigDecimal getAmout() {
		return get("amout");
	}

	public M setEnable(java.lang.Integer enable) {
		set("enable", enable);
		return (M)this;
	}
	
	public java.lang.Integer getEnable() {
		return getInt("enable");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setVersion(java.lang.Integer version) {
		set("version", version);
		return (M)this;
	}
	
	public java.lang.Integer getVersion() {
		return getInt("version");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setMemo(java.lang.String memo) {
		set("memo", memo);
		return (M)this;
	}
	
	public java.lang.String getMemo() {
		return getStr("memo");
	}

	public M setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
		return (M)this;
	}
	
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}

	public M setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.lang.String getCreateTime() {
		return getStr("create_time");
	}

	public M setUpdateTime(java.lang.String updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.lang.String getUpdateTime() {
		return getStr("update_time");
	}

	public M setSerialId(java.lang.String serialId) {
		set("serial_id", serialId);
		return (M)this;
	}
	
	public java.lang.String getSerialId() {
		return getStr("serial_id");
	}

}
