package com.ns.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTldAwardMid<M extends BaseTldAwardMid<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setPostNo(java.lang.String postNo) {
		set("post_no", postNo);
		return (M)this;
	}
	
	public java.lang.String getPostNo() {
		return getStr("post_no");
	}

	public M setPostName(java.lang.String postName) {
		set("post_name", postName);
		return (M)this;
	}
	
	public java.lang.String getPostName() {
		return getStr("post_name");
	}

	public M setConId(java.lang.String conId) {
		set("con_id", conId);
		return (M)this;
	}
	
	public java.lang.String getConId() {
		return getStr("con_id");
	}

	public M setConNo(java.lang.String conNo) {
		set("con_no", conNo);
		return (M)this;
	}
	
	public java.lang.String getConNo() {
		return getStr("con_no");
	}

	public M setConName(java.lang.String conName) {
		set("con_name", conName);
		return (M)this;
	}
	
	public java.lang.String getConName() {
		return getStr("con_name");
	}

	public M setMobile(java.lang.String mobile) {
		set("mobile", mobile);
		return (M)this;
	}
	
	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	public M setEnable(java.lang.Integer enable) {
		set("enable", enable);
		return (M)this;
	}
	
	public java.lang.Integer getEnable() {
		return getInt("enable");
	}

	public M setVersion(java.lang.Integer version) {
		set("version", version);
		return (M)this;
	}
	
	public java.lang.Integer getVersion() {
		return getInt("version");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setMemo(java.lang.String memo) {
		set("memo", memo);
		return (M)this;
	}
	
	public java.lang.String getMemo() {
		return getStr("memo");
	}

	public M setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
		return (M)this;
	}
	
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}

	public M setCreateDt(java.lang.String createDt) {
		set("create_dt", createDt);
		return (M)this;
	}
	
	public java.lang.String getCreateDt() {
		return getStr("create_dt");
	}

	public M setUpdateDt(java.lang.String updateDt) {
		set("update_dt", updateDt);
		return (M)this;
	}
	
	public java.lang.String getUpdateDt() {
		return getStr("update_dt");
	}

	public M setMinDate(java.lang.String minDate) {
		set("min_date", minDate);
		return (M)this;
	}
	
	public java.lang.String getMinDate() {
		return getStr("min_date");
	}

	public M setYear(java.lang.String year) {
		set("year", year);
		return (M)this;
	}
	
	public java.lang.String getYear() {
		return getStr("year");
	}

	public M setMonth(java.lang.String month) {
		set("month", month);
		return (M)this;
	}
	
	public java.lang.String getMonth() {
		return getStr("month");
	}

	public M setDirectPush(java.lang.Integer directPush) {
		set("direct_push", directPush);
		return (M)this;
	}
	
	public java.lang.Integer getDirectPush() {
		return getInt("direct_push");
	}

	public M setConTotal(java.lang.Integer conTotal) {
		set("con_total", conTotal);
		return (M)this;
	}
	
	public java.lang.Integer getConTotal() {
		return getInt("con_total");
	}

	public M setMonthSale(java.math.BigDecimal monthSale) {
		set("month_sale", monthSale);
		return (M)this;
	}
	
	public java.math.BigDecimal getMonthSale() {
		return get("month_sale");
	}

	public M setPercent(java.math.BigDecimal percent) {
		set("percent", percent);
		return (M)this;
	}
	
	public java.math.BigDecimal getPercent() {
		return get("percent");
	}

	public M setDay(java.lang.String day) {
		set("day", day);
		return (M)this;
	}
	
	public java.lang.String getDay() {
		return getStr("day");
	}

}
