package com.ns.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTldPntParams<M extends BaseTldPntParams<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setProductId(java.lang.String productId) {
		set("product_id", productId);
		return (M)this;
	}
	
	public java.lang.String getProductId() {
		return getStr("product_id");
	}

	public M setProductName(java.lang.String productName) {
		set("product_name", productName);
		return (M)this;
	}
	
	public java.lang.String getProductName() {
		return getStr("product_name");
	}

	public M setSkuId(java.lang.String skuId) {
		set("sku_id", skuId);
		return (M)this;
	}
	
	public java.lang.String getSkuId() {
		return getStr("sku_id");
	}

	public M setSkuName(java.lang.String skuName) {
		set("sku_name", skuName);
		return (M)this;
	}
	
	public java.lang.String getSkuName() {
		return getStr("sku_name");
	}

	public M setPostNo(java.lang.String postNo) {
		set("post_no", postNo);
		return (M)this;
	}
	
	public java.lang.String getPostNo() {
		return getStr("post_no");
	}

	public M setPostName(java.lang.String postName) {
		set("post_name", postName);
		return (M)this;
	}
	
	public java.lang.String getPostName() {
		return getStr("post_name");
	}

	public M setPercent(java.math.BigDecimal percent) {
		set("percent", percent);
		return (M)this;
	}
	
	public java.math.BigDecimal getPercent() {
		return get("percent");
	}

	public M setRepercent(java.math.BigDecimal repercent) {
		set("repercent", repercent);
		return (M)this;
	}
	
	public java.math.BigDecimal getRepercent() {
		return get("repercent");
	}

	public M setEnable(java.lang.Integer enable) {
		set("enable", enable);
		return (M)this;
	}
	
	public java.lang.Integer getEnable() {
		return getInt("enable");
	}

	public M setVersion(java.lang.Integer version) {
		set("version", version);
		return (M)this;
	}
	
	public java.lang.Integer getVersion() {
		return getInt("version");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setMemo(java.lang.String memo) {
		set("memo", memo);
		return (M)this;
	}
	
	public java.lang.String getMemo() {
		return getStr("memo");
	}

	public M setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
		return (M)this;
	}
	
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}

	public M setCreateDt(java.lang.String createDt) {
		set("create_dt", createDt);
		return (M)this;
	}
	
	public java.lang.String getCreateDt() {
		return getStr("create_dt");
	}

	public M setUpdateDt(java.lang.String updateDt) {
		set("update_dt", updateDt);
		return (M)this;
	}
	
	public java.lang.String getUpdateDt() {
		return getStr("update_dt");
	}

}
