package com.ns.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTldWechatWithdraw<M extends BaseTldWechatWithdraw<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setSerialId(java.lang.String serialId) {
		set("serial_id", serialId);
		return (M)this;
	}
	
	public java.lang.String getSerialId() {
		return getStr("serial_id");
	}

	public M setOpenId(java.lang.String openId) {
		set("open_id", openId);
		return (M)this;
	}
	
	public java.lang.String getOpenId() {
		return getStr("open_id");
	}

	public M setWechatResult(java.lang.String wechatResult) {
		set("wechat_result", wechatResult);
		return (M)this;
	}
	
	public java.lang.String getWechatResult() {
		return getStr("wechat_result");
	}

	public M setBizResult(java.lang.String bizResult) {
		set("biz_result", bizResult);
		return (M)this;
	}
	
	public java.lang.String getBizResult() {
		return getStr("biz_result");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setCreateDt(java.lang.String createDt) {
		set("create_dt", createDt);
		return (M)this;
	}
	
	public java.lang.String getCreateDt() {
		return getStr("create_dt");
	}

	public M setIsConfirm(java.lang.Integer isConfirm) {
		set("is_confirm", isConfirm);
		return (M)this;
	}
	
	public java.lang.Integer getIsConfirm() {
		return getInt("is_confirm");
	}

	public M setQryWechatMsg(java.lang.String qryWechatMsg) {
		set("qry_wechat_msg", qryWechatMsg);
		return (M)this;
	}
	
	public java.lang.String getQryWechatMsg() {
		return getStr("qry_wechat_msg");
	}

	public M setUpdateDt(java.lang.String updateDt) {
		set("update_dt", updateDt);
		return (M)this;
	}
	
	public java.lang.String getUpdateDt() {
		return getStr("update_dt");
	}

}
